# Generated by Django 4.1.2 on 2022-10-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('processor_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_cores', models.IntegerField()),
                ('number_of_usb_ports', models.IntegerField()),
                ('number_of_hdmi_ports', models.IntegerField()),
            ],
        ),
    ]
