# Generated by Django 4.1.2 on 2022-10-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0002_mouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('has_numeric_keypad', models.CharField(max_length=100)),
                ('has_backlight', models.CharField(max_length=100)),
            ],
        ),
    ]
